# -*- coding: utf-8 -*-
"""可见 AI 标识取证（tools/ai_label_tool.py）+ 规则引擎接入的回归测试

为什么要有这组测试：
    这个工具的价值全在「判得准」和「不乱判」两件事上。
    乱判（把真实图的高分关键词当 AI 标识）会制造假阳性，代价是误伤真实内容；
    漏判（标识写法千奇百怪）会让这个补偿手段形同虚设。
    所以正例（各种写法）、反例（普通文案、只有平台名）、阈值边界、规则引擎接入都要钉死。
"""
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tools"))
sys.path.insert(0, str(REPO))

import ai_label_tool  # noqa: E402
import rule_engine  # noqa: E402


def line(text, conf=0.99, bbox=(0, 0, 10, 10)):
    return {"text": text, "confidence": conf, "bbox": list(bbox)}


# ---------------------------------------------------------------- 正例：各种写法都要认
@pytest.mark.parametrize("text", [
    "AI生成",
    "AI 生成",          # 平台角标常见写法带空格
    "AI生成内容",
    "由AI生成",
    "AI绘制",
    "人工智能生成",
    "本图由AI生成",
    "AIGC生成",
    "Generated by AI",
    "AI-generated",
    "Made with AI",
])
def test_detects_ai_label_variants(text):
    hits = ai_label_tool.detect([line(text)])
    assert any(h["accepted"] for h in hits), f"没认出这类标识写法: {text}"


def test_generates_build_evidence_shape():
    ev = ai_label_tool.build_evidence("dummy.png", [line("AI生成", 0.97), line("口红试用装", 0.9)])
    assert ev["tool"] == "ai_label"
    assert ev["ai_label_detected"] is True
    first = ev["evidence"][0]
    assert first["best_hit"]["text"] == "AI生成"
    assert first["best_hit"]["confidence"] == 0.97
    # 诚实边界必须写在证据里，不能只写在代码注释里
    assert "不证明" in ev["cannot_prove"]
    assert "洗掉标识" in ev["cannot_prove"]


def test_generator_hint_captured_but_not_triggering_alone():
    """平台名只作溯源信息，单独出现不足以定级（否则普通水印图会被乱判）。"""
    hits = ai_label_tool.detect([line("midjourney v6")])
    assert not any(h["accepted"] for h in hits)
    ev = ai_label_tool.build_evidence("dummy.png", [line("AI生成  Midjourney", 0.99)])
    assert ev["evidence"][0]["best_hit"]["generator_hint"] == "midjourney"


# ---------------------------------------------------------------- 反例：不能乱判
@pytest.mark.parametrize("text", [
    "口红试用装", "限时优惠 买一送一", "成分党必看", "自然堂 补水面膜",
    "防晒霜推荐 SPF50+", "使用方法：洁面后取适量",
])
def test_no_false_positive_on_ordinary_copy(text):
    """真实种草图上的普通文案绝不能被当成 AI 标识 —— 误伤真实内容的代价最高。"""
    assert not ai_label_tool.detect([line(text)])


def test_low_confidence_is_not_accepted():
    """抄得不像就不采信：conf 低于门槛只能记录，不能定级。"""
    hits = ai_label_tool.detect([line("AI生成", 0.60)])
    assert hits and not hits[0]["accepted"]
    assert "置信度" in hits[0]["reject_reason"]


def test_empty_input_is_safe():
    assert ai_label_tool.detect([]) == []
    ev = ai_label_tool.build_evidence("dummy.png", [])
    assert ev["ai_label_detected"] is False


# ---------------------------------------------------------------- 规则引擎接入
def test_judge_escalates_to_high_risk_on_label():
    ev = ai_label_tool.build_evidence("dummy.png", [line("AI生成", 0.99)])
    level, reasons = rule_engine.judge({"ai_label": ev})
    assert level == "high_risk"
    assert any("可见AI标识" in r for r in reasons)


def test_judge_does_nothing_without_hit():
    ev = ai_label_tool.build_evidence("dummy.png", [line("口红试用装", 0.99)])
    level, reasons = rule_engine.judge({"ai_label": ev})
    assert level != "high_risk"
    assert any("可见AI标识" in r for r in reasons)


def test_switch_off_keeps_judgement_neutral():
    ev = ai_label_tool.build_evidence("dummy.png", [line("AI生成", 0.99)])
    old = rule_engine.AI_LABEL_TRIGGERS_RISK
    try:
        rule_engine.AI_LABEL_TRIGGERS_RISK = False
        level, reasons = rule_engine.judge({"ai_label": ev})
        assert level != "high_risk"
        assert any("不参与自动定级" in r for r in reasons)
    finally:
        rule_engine.AI_LABEL_TRIGGERS_RISK = old


def test_explain_returns_all_fields_on_label_path():
    """explain() 历史坑：按风险分支写文案，漏一个字段就 UnboundLocalError。这里钉死四字段齐全。"""
    ev = ai_label_tool.build_evidence("dummy.png", [line("AI生成", 0.99)])
    out = rule_engine.explain("high_risk", {"ai_label": ev})
    for k in ("headline", "summary", "what_to_do", "caveat", "action_playbook"):
        assert k in out and out[k], f"explain() 缺字段 {k}"
    assert "AI生成" in out["headline"] or "AI生成" in out["summary"]
    # 标识可伪造的边界必须出现在给用户看的提醒里
    assert "伪造" in out["caveat"]
